######################################################
################# Setup Ceph #########################
######################################################
---
- name: Setup Ceph
  block:
    - import_tasks: 00_preflight.yml
    - import_tasks: 05_files.yml
    - import_tasks: 10_install.yml
    - import_tasks: 15_setup.yml
    - import_tasks: 20_deploy.yml
    - import_tasks: 25_validate.yml
  when: inventory_hostname in groups['master-server']
...
